name: Test1
on:
  workflow_dispatch: # Allows you to trigger this manually
  push:              # Optional, triggers when code is pushed

jobs:
  trigger-repo-a:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Repo A Workflow
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${{ secrets.REPO_A_TOKEN }}" \
            https://api.github.com/repos/Robert2305/Github-library-Generic/dispatches \
            -d '{"event_type":"run-jobs"}'